apiVersion: v1
kind: Pod
metadata:
  name: appname
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - mountPath: /etc/cars
        name: car-vol
  volumes:
    - name: car-vol
    configMap:
      name: fast-car

