apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sleepy5
spec:
  schedule: "* / 2 * * * *"
  jobTemplate:
   spec:
      template:
       spec:
        containers:
        - name: resting10
          image: busybox
          command: ["/bin/sleep"]
          args: ["3"]
        restartPolicy: Never


                            
