apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sleepy5
spec:
  schedule: "* / 2 * * * *"
  jobTemplate:
   spec:
      template:
       spec:
        containers:
        - name: resting10
          image: busybox
          command: ["/bin/sleep"]
          args: ["3"]
        restartPolicy: Never

---

apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
spec:
  containers:
  - image: kodekloud/fileserver
    name: gop-fileserver

    volumeMounts:
    - name: data-store
      mountPath: /web

  volumes:
  - name: data-store
    persistentVolumeClaim:
      claimName: data-pvc
                            