
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-one
spec:
  selector:
    matchLabels:
     system: ds-one
  template:
    metadata:
      labels: 
        system: ds-one
    spec:
      containers:
        - name: nginx
          image: nginx:1.15.1
          ports:
            - containerPort: 80
