We already have a secret key file media.txt under /opt location on jump host. Create a generic secret named media, 
it should contain the password/license-number present in media.txt file.
Also create a pod named secret-devops.
Configure pod's spec as container name should be secret-container-devops, image should be centos preferably with latest tag (remember to mention the tag with image). Use sleep command for container so that it remains in running state. Consume the created secret and mount it under /opt/games within the container.
To verify you can exec into the container secret-container-devops, to check the secret key under the mounted path /opt/games.
---
/opt$ echo -n '5ecur3' | base64
---
/opt$ cat secret.yaml 
apiVersion: v1
kind: Secret
metadata:
  name: media
type: Generic
data:
   password-license-number: NWVjdXIz 
   
---

/opt$ cat pod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: secret-devops
spec:
  containers:
  - name: secret-container-devops
    image: centos:latest
    command: ["/bin/bash","-c","sleep 1d"]
    volumeMounts:
    - name: secret-volume
      mountPath: "/opt/games"
  volumes:
  - name: secret-volume
    secret:
      secretName: media
