apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  selector:
    matchLabels:
      app: httpd-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: httpd-frontend
    spec:
      containers:
      - name: alpine
        image: httpd:2.4-alpine
        
