apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  resources:
    requests:
      storage: 1Gi
# volumeMode: Filesystem
  accessModes:
    - ReadWriteMany


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-alpha-pvc
  namespace: alpha
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: slow    
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce