apiVersion: v1
 kind: Pod
 metadata:
   name: qos-besteffort
   namespace: qos
 spec:
   containers:
   - name: qos-g
     image: nginx
     resources:
       requests:
         memory: "100Mi"
         cpu: "400m"

--

$ kubectl get pod qos-best --namespace=qos-example --output=yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
\
\name: qos-best
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-08-09T15:37:27Z"
  hostIP: 192.168.1.105
  phase: Running
  podIP: 10.245.89.32
  podIPs:
  - ip: 10.245.89.32
  qosClass: Burstable  <--------- Best Effort --------------------->
  startTime: "2021-08-09T15:37:21Z
\
\
