apiVersion: v1
kind: Pod
metadata:
  name: qos-burst-2
  namespace: qos-example
spec:
  containers:
  - name: qos-burst-2
    image: nginx
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"

----

$ kubectl get pod qos-burst-2 --namespace=qos-example --output=yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
\
\
\
name: qos-burst-2
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-08-09T15:57:52Z"
  hostIP: 192.168.1.105
  phase: Running
  podIP: 10.245.89.43
  podIPs:
  - ip: 10.245.89.43
  qosClass: Burstable   < ------------ Burstable more than limit ---------- >
  startTime: "2021-08-09T15:57:46Z"
