apiVersion: v1
kind: Pod
metadata:
  name: qos-guaranteed
  namespace: qos
spec:
  containers:
  - name: qos-g
    image: nginx
    resources:
      limits:
        memory: "100Mi"
        cpu: "400m"
      requests:
        memory: "100Mi"
        cpu: "400m"
        
        
        
        $ kubectl get pod qos-demo --namespace=qos-example --output=yaml
apiVersion: v1
kind: Pod
metadata:
/
/
/
   name: qos-guaranteed
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-08-09T14:52:45Z"
  hostIP: 192.168.1.105
  phase: Running
  podIP: 10.245.89.44
  podIPs:
  - ip: 10.245.89.44
  qosClass: Guaranteed    <-------------- Guaranteed QOS ----------------->
  startTime: "2021-08-09T14:52:39Z"
