# Create a pod named webserver.

# Create an emptyDir volume shared-logs.

# Create two containers from nginx and ubuntu images with latest tag only and remember to mention tag i.e nginx:latest, nginx container name should be nginx-container and ubuntu container name should be sidecar-container on webserver pod.

# Add command on sidecar-container "sh","-c","while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done"


apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webserver
  name: webserver
spec:
  containers:
  - image: nginx:latest
    name: nginx-container
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
  - image: ubuntu:latest
    name: sidecar-container
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
    command: ["sh","-c","while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done"]
  volumes:
  - name: shared-logs
    emptyDir: {}
