---
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: datacenter
data:
  TIME_FREQ: "7"

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: time-check
  name: time-check
  namespace : datacenter
spec:
  containers:
  - image: busybox:latest
    name: time-check
    command: ["/bin/sh","-c"]
    args:
        [
          "while true; do date; sleep $TIME_FREQ;done > /opt/security/time/time-check.log",
 ]
    volumeMounts:
    - mountPath: /opt/security/time/
      name: log-volume
    envFrom:
        - configMapRef:
            name: time-config
  volumes:
  - name: log-volume
