kubectl create ns devops

---
cat configmaptime.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: devops
data:
  TIME_FREQ: "8"

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: time-check
  name: time-check
  namespace : devops
spec:
  containers:
  - image: busybox:latest
    name: time-check
    command: ["/bin/sh","-c","while true; do date; sleep $TIME_FREQ; done"]
    volumeMounts:
    - mountPath: /opt/data/time/
      name: log-volume
    env:
    - name: TIME_FREQ
      valueFrom:
        configMapKeyRef:
              name: time-config
              key: TIME_FREQ 
  volumes:
  - name: log-volume
  
  ---
  
  kubectl -n devops logs time-check
Sun Aug 15 20:05:22 UTC 2021
Sun Aug 15 20:05:30 UTC 2021
Sun Aug 15 20:05:38 UTC 2021
Sun Aug 15 20:05:46 UTC 2021
    
